baseURL = 'https://findsofun.com/'
defaultContentLanguage = 'zh-cn'
defaultContentLanguageInSubdir = false
theme =["hugo-shares-themes","notion-site-theme"]
pagination.pagerSize = 9
summaryLength = 20

[languages]
  [languages.zh-cn]
    languageCode = 'zh-CN'
    languageName = '中文'
    title = "FindSoFun - 发现有趣AI工具与前端组件库"
    weight = 1

  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    title = "FindSoFun - Discover Interesting AI Tools & Frontend Libraries"
    weight = 2

[languages.zh-cn.params]
description = "专业的AI工具推荐和前端组件库分享平台。发现最新的AI工具、开发工具、设计资源，提升工作效率。每日更新，精选优质内容。"
mainSections = 'posts'
welcomeMessage = "欢迎来到FindSoFun，发现有趣的工具！"
defaultImage = "/images/default-social.png"
keywords = ["AI工具", "前端组件库", "开发工具", "设计资源", "效率工具", "技术分享"]

[languages.zh-cn.params.author]
name = 'nonacosa'
bio = 'I love exploring tech and sharing fun things I discover!'
avatar = '/images/avatar.jpeg'
projectGithub = 'https://www.github.com/nonacosa/notion-site'
github = 'https://www.github.com/nonacosa/'
linkedin = 'https://www.linkedin.com/in/jacob-a-horton/'
x = 'https://x.com/sis_nonacosa/'

[languages.en.params]
description = "Professional AI tools and frontend library sharing platform. Discover the latest AI tools, development tools, design resources to improve work efficiency. Daily updates with curated quality content."
mainSections = 'posts'
welcomeMessage = "Welcome to FindSoFun, discover interesting tools!"
defaultImage = "/images/default-social.png"
keywords = ["AI Tools", "Frontend Libraries", "Development Tools", "Design Resources", "Productivity Tools", "Tech Sharing"]

[languages.en.params.author]
name = 'nonacosa'
bio = 'I love exploring tech and sharing fun things I discover!'
avatar = '/images/avatar.jpeg'
projectGithub = 'https://www.github.com/nonacosa/notion-site'
github = 'https://www.github.com/nonacosa/'
linkedin = 'https://www.linkedin.com/in/jacob-a-horton/'
x = 'https://x.com/sis_nonacosa/'

[languages.zh-cn.menu]
[[languages.zh-cn.menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[languages.zh-cn.menu.main]]
name = 'About'
pageRef = '/about'
weight = 15

[[languages.zh-cn.menu.main]]
name = 'Tags'
pageRef = '/tags'
weight = 20

[languages.en.menu]
[[languages.en.menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[languages.en.menu.main]]
name = 'About'
pageRef = '/about'
weight = 15

[[languages.en.menu.main]]
name = 'Tags'
pageRef = '/tags'
weight = 20

[module]

[module.hugoVersion]
extended = false
min = "0.116.0"

[module.mounts] # Directing the static folder to assets.
source = 'assets'
target = 'static'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"

[frontmatter]
  preserveTaxonomyNames = false  # 允许 Hugo 自动 slugify 中文 tag

[permalinks]
  posts = "/:slug/"
  tags = "/tags/:slug/"   